// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRkdkLm623Lrypaw_bmRzRIepN9oF-AzM',
    appId: '1:631138056518:web:e5891a597f9e5a55eacd47',
    messagingSenderId: '631138056518',
    projectId: 'bluestar-7e25a',
    authDomain: 'bluestar-7e25a.firebaseapp.com',
    storageBucket: 'bluestar-7e25a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuo_rA9QMziQ7g9DQ_HPadzOvJq496jgU',
    appId: '1:631138056518:android:fc38ef7f40af90bdeacd47',
    messagingSenderId: '631138056518',
    projectId: 'bluestar-7e25a',
    storageBucket: 'bluestar-7e25a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW-Y40GZDYRdPH6UaVi4ZlHj0RhsVacxw',
    appId: '1:631138056518:ios:bc0289c6e5e43d5feacd47',
    messagingSenderId: '631138056518',
    projectId: 'bluestar-7e25a',
    storageBucket: 'bluestar-7e25a.firebasestorage.app',
    iosBundleId: 'com.example.cateyePos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW-Y40GZDYRdPH6UaVi4ZlHj0RhsVacxw',
    appId: '1:631138056518:ios:bc0289c6e5e43d5feacd47',
    messagingSenderId: '631138056518',
    projectId: 'bluestar-7e25a',
    storageBucket: 'bluestar-7e25a.firebasestorage.app',
    iosBundleId: 'com.example.cateyePos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRkdkLm623Lrypaw_bmRzRIepN9oF-AzM',
    appId: '1:631138056518:web:0d7f09714147d9baeacd47',
    messagingSenderId: '631138056518',
    projectId: 'bluestar-7e25a',
    authDomain: 'bluestar-7e25a.firebaseapp.com',
    storageBucket: 'bluestar-7e25a.firebasestorage.app',
  );

}